### ISSUE TITLE
Move modules.json to tessel.io and close this repo?

### ISSUE THREAD

**Issue by Frijol** [tessel/hardware-modules#14]
I think the only real advantage of this repo is the modules.json file. We only use this file for tessel.io. I propose that we move modules.json to tessel.io, re-link as necessary, and close this repo.

cc @tcr

**Comment by johnnyman727** [comment]
My two cents is that it sounds like not the most important thing but a good idea to do eventually.

**Comment by Frijol** [comment]
@tcr can this be part of the transition to tessel-www?
